name: 'Custom Env Vars'

on:
  workflow_dispatch:

# Scoped to entire workflow
env:
  DAY_OF_WEEK: Funday
  testvar: value-1

jobs:
  mainJob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    # Scoped to job
    env:
      Greeting: Dear
      testvar: value-2

    steps:
    - name: print-values-of-env-vars
      run:
        echo "$Greeting $First_name. Today is $DAY_OF_WEEK!"
        echo "testvar $testvar"
        echo "testvar ${{ env.testvar }}"
        
      # Scoped to steps inside job
      env:
        First_Name: Student
        testvar: value-3
